### ISSUE TITLE
資料來源使用 https

### ISSUE THREAD

**Issue by bestpika** [banqhsia/TRA-Info#1]
嗨，你用的那個資料來源其實是有提供 https 連線的
所以可以請你抓資料那段使用 https 抓嗎
謝謝

**Comment by banqhsia** [comment]
感謝您的建議，由於 `ptx.transportdata.tw` 此網域使用  self-signed certificate，未經由使用者主動按下「同意並前往」的瀏覽器，會主動阻擋該網域回傳的資料，並且收到 `ERR_INSECURE_RESPONSE` 的錯誤。

**Comment by bestpika** [comment]
不對吧，我看到的憑證是政府憑證管理中心發的並不是自我簽署喔

**Comment by banqhsia** [comment]
這真的是太奇怪了，我在 Mac 的 Chrome 及 Safari 皆會出現錯誤

![2016-11-26 10 12 24](https://cloud.githubusercontent.com/assets/4393788/20640900/e339da54-b426-11e6-80c6-950a7fe4a320.png)

![2016-11-26 10 18 12](https://cloud.githubusercontent.com/assets/4393788/20640902/e7830284-b426-11e6-93f6-6b0b6e4c6c71.png)

我再使用其他環境測試看看，感謝謝你提供的建議

**Comment by bestpika** [comment]
我本來還以為你是 Firefox 不信任，這個我知道原因只能去找 Mozilla 而已
而且是新的憑證他們沒加的問題，至於為什麼...可能真的要問神

底下是我的 Chrome 上面標的
![image](https://cloud.githubusercontent.com/assets/5698157/20641010/40708d1a-b429-11e6-9146-af874125b457.png)
![image](https://cloud.githubusercontent.com/assets/5698157/20641023/7fbc9086-b429-11e6-867c-b52ba8a759fa.png)

**Comment by banqhsia** [comment]
Thanks for suggestion. The error doesn't show anymore. And all the data links have been changed to HTTPS.  

58ba187bd40a30dffe1fb3b1150267af45f0e9f1
